export const mutations = {
  UPDATE_QUIZES_LOADING: 'UPDATE_QUIZES_LOADING',
  UPDATE_QUIZES_DATA: 'UPDATE_QUIZES_DATA',
  UPDATE_QUIZE_LOADING: 'UPDATE_QUIZE_LOADING',
};

export const actions = {
  GET_QUIZES: 'GET_QUIZES',
  CREATE_QUIZ: 'CREATE_QUIZ',
};
